server: 
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: gateaway
          uri: https://github.com/DiegoFuentes33/Microservicios-Tutorial
          search-paths: config-data
  application:
    name: config-service